## ProgrammingAssignment2

## makeCacheMatrix prepares a list processed then by cacheSolve using a raw matrix to be inverted as an argument

makeCacheMatrix <- function(x = matrix()) {
    sol <- NULL
    set <- function(y) {
        x <<- y
        sol <<- NULL
    }
    get <- function() x
    setsolve <-function(solve) sol <<- solve
    getsolve <-function() sol
    list(set = set, get = get,
         setsolve = setsolve,
         getsolve = getsolve)
}


## cacheSolve inverts matrix x using a list generated by makeCacheMatrix from a raw matrix as an argument

cacheSolve <- function(x, ...) {

    sol <- x$getsolve()
    if (!is.null(sol)){
        message("getting cached data")
        return(sol)
    }
    data <- x$get()
    sol <- solve(data, ...)
    x$setsolve(sol)
        ## Return a matrix that is the inverse of 'x'
    sol
}
